name: Deploy Homelab Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy and restart services
        run: |
          cd /home/markoserver/docker
          git pull origin main
          cd dashboard
          docker compose up -d
